function modal(space){
 return `<div class="modal-backdrop" data-close-modal><article class="item-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onclick="event.stopPropagation()"><div class="item-image"><img src="${escapeHTML(space.image)}" alt="${escapeHTML(space.title)}"></div><div class="item-details"><button class="modal-close" aria-label="Close" data-close-modal>×</button><div class="kicker">${escapeHTML(space.disclosure)}</div><h2 id="modal-title">${escapeHTML(space.title)}</h2><p>${escapeHTML(space.subtitle)}</p><div class="meta-row"><span class="meta-chip">Used by ${escapeHTML(profile.name)}</span><span class="meta-chip">Last updated Sep 2026</span><span class="meta-chip">${escapeHTML(space.disclosure)}</span></div><div class="item-quote">${escapeHTML(space.note)}</div><div class="item-actions"><button class="pill" data-save="${space.id}">♡ Save</button><button class="pill story-cta" data-share-space="${space.id}">Story ↗</button><a class="pill light" href="${escapeHTML(space.url||'#')}" target="_blank" rel="nofollow sponsored noopener">View recommendation ↗</a></div><div class="disclosure">Disclosure: ${escapeHTML(space.disclosure)}. If an affiliate link is used, the creator may earn a commission without changing your price.</div></div></article></div>`
}

function storySheet({space=null,previewUrl=''}){
 const isProfile=!space;
 const label=isProfile?`${profile.name}'s Zat`:`${profile.name} · ${space.title}`;
 const shareUrl=absoluteShareUrl(space);
 return `<div class="story-backdrop" data-close-story><section class="story-sheet" role="dialog" aria-modal="true" aria-label="Share story" onclick="event.stopPropagation()">
  <div class="story-sheet-head"><div><span class="kicker">Story Studio</span><h2>${escapeHTML(label)}</h2></div><button class="modal-close" data-close-story aria-label="Close">×</button></div>
  <div class="story-workspace">
   <div class="story-phone"><div class="story-generating" id="story-generating"><span class="story-spinner"></span><b>Generating 9:16 story…</b></div><img id="story-preview-image" alt="Generated story preview" ${previewUrl?`src="${previewUrl}"`:''}></div>
   <div class="story-controls"><div class="story-copy"><span class="meta-chip">1080 × 1920</span><span class="meta-chip">Instagram Story ready</span><span class="meta-chip">Native share</span></div><p>${isProfile?'A complete profile story featuring the creator and selected Spaces.':'A share card for this Space, including context, disclosure and a direct Zat link.'}</p>
   <div class="story-url"><span>${escapeHTML(shareUrl)}</span><button data-copy-link>Copy</button></div>
   <button class="pill light story-primary" data-native-share>Share to Instagram / apps ↗</button>
   <button class="pill story-secondary" data-download-story>Save story image</button>
   <button class="pill story-secondary" data-copy-link>Copy share link</button>
   <small>On iPhone and Android, “Share” opens the system share sheet. If Instagram is installed it can appear there. Web browsers cannot silently publish to a user's Instagram account without the user choosing the destination.</small>
   </div>
  </div>
 </section></div>`
}

function studioPage(){
 const spaces=(profile.spaces||[]).slice(0,8);
 return `<main id="app" class="studio"><nav class="studio-nav">${brand()}<div style="display:flex;gap:8px"><a class="pill" href="/${escapeHTML(profile.username||'alex')}" data-nav>Preview profile</a><button class="pill light" id="save-profile">Save changes</button></div></nav><div class="studio-shell"><aside class="studio-side"><button class="active">Profile editor</button><button>Spaces</button><button>Story sharing</button><button>Analytics</button><button>Affiliate links</button><button>Brand settings</button><a href="/pricing" data-nav>Plan & billing</a></aside><section class="studio-main"><div class="studio-header"><div><div class="kicker">Creator Studio</div><h1>Shape your Zat.</h1><p>Everything here updates the public profile and its share cards.</p></div><span class="pill">zat.example/${escapeHTML(profile.username)}</span></div><div class="editor-grid"><div class="panel"><h2>Identity</h2>${field('Name','name',profile.name)}${field('Username','username',profile.username)}${field('City','city',profile.city)}${field('Headline','headline',profile.headline)}${field('Roles','roles',profile.roles)}${textarea('Bio','bio',profile.bio)}</div><div class="panel"><h2>Visual identity</h2>${field('Avatar image URL','avatar',profile.avatar)}<div class="field"><label>Live avatar</label><div style="height:290px;display:grid;place-items:center;border:1px solid var(--hair);border-radius:16px;background:#0b0c0d;overflow:hidden"><img src="${escapeHTML(profile.avatar)}" style="height:100%;object-fit:contain" alt="Avatar preview"></div></div><button class="pill" data-share-profile>Generate profile story ↗</button></div><div class="panel full"><h2>Spaces</h2><div class="space-editor-list">${spaces.map((s,i)=>spaceEditor(s,i)).join('')}</div><div class="studio-actions"><button class="pill" id="reset-profile">Reset demo</button><button class="pill light" id="save-profile-bottom">Save profile</button></div></div></div></section></div></main>`;
}
function field(label,key,value){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" data-profile-key="${key}" value="${escapeHTML(value)}"></div>`}
function textarea(label,key,value){return `<div class="field"><label for="${key}">${label}</label><textarea id="${key}" data-profile-key="${key}">${escapeHTML(value)}</textarea></div>`}
function spaceEditor(s,i){return `<div class="space-edit" data-space-editor="${i}"><div class="space-edit-head"><b>${String(i+1).padStart(2,'0')} ${escapeHTML(s.title)}</b><span class="muted">${escapeHTML(s.disclosure)}</span></div>${fieldMini('Title','title',s.title,i)}${fieldMini('Subtitle','subtitle',s.subtitle,i)}${fieldMini('Image URL','image',s.image,i)}${fieldMini('Product / label','product',s.product,i)}${fieldMini('Outbound URL','url',s.url,i)}<div class="field"><label>Disclosure</label><select data-space-index="${i}" data-space-key="disclosure"><option ${s.disclosure==='Purchased myself'?'selected':''}>Purchased myself</option><option ${s.disclosure==='Affiliate'?'selected':''}>Affiliate</option><option ${s.disclosure==='Gifted'?'selected':''}>Gifted</option><option ${s.disclosure==='Sponsored'?'selected':''}>Sponsored</option><option ${s.disclosure==='Editorial'?'selected':''}>Editorial</option></select></div><button class="pill" data-share-space="${s.id}">Generate story ↗</button></div>`}
function fieldMini(label,key,value,i){return `<div class="field"><label>${label}</label><input data-space-index="${i}" data-space-key="${key}" value="${escapeHTML(value)}"></div>`}

function pricingPage(){return `<main id="app" class="pricing-page"><nav class="marketing-nav">${brand()}<div class="marketing-links">${navLink('Profile demo','/alex')} ${navLink('Studio','/studio')} <a class="pill light" href="/studio" data-nav>Start free ↗</a></div></nav><section class="pricing-content"><div class="kicker" style="text-align:center">Simple creator pricing</div><h1>Own the destination.</h1><p class="muted">Start with a polished profile. Upgrade when you need custom domains, deeper analytics and commerce tools.</p><div class="pricing-grid">${priceCard('Free','£0',['1 public Zat profile','8 Spaces','Basic click analytics','Story sharing','Zat branding'],'Start free')}${priceCard('Creator','£12',['Unlimited Spaces','Custom domain','Advanced analytics','Affiliate link tools','Story templates','Remove Zat branding'],'Choose Creator',true)}${priceCard('Pro','£29',['Everything in Creator','Audience capture','Brand media kit','Team access','Advanced attribution'],'Choose Pro')}</div></section></main>`}
function priceCard(name,price,items,cta,featured=false){return `<article class="price-card ${featured?'featured':''}"><div class="kicker">${name}</div><div class="price">${price}<small>/month</small></div><p class="muted">${name==='Free'?'For trying the format.':name==='Creator'?'For creators turning attention into a business.':'For professional creators and small teams.'}</p><ul class="price-list">${items.map(x=>`<li>${x}</li>`).join('')}</ul><a class="pill" href="/studio" data-nav>${cta} ↗</a></article>`}

async function saveProfile(){
  document.querySelectorAll('[data-profile-key]').forEach(el=>profile[el.dataset.profileKey]=el.value.trim());
  document.querySelectorAll('[data-space-index]').forEach(el=>{const i=+el.dataset.spaceIndex;profile.spaces[i][el.dataset.spaceKey]=el.value.trim()});
  try{localStorage.setItem(`zat:${profile.username||'alex'}`,JSON.stringify(profile))}catch{}
  if(serverAvailable){
    const token=sessionStorage.getItem('zat-admin-token')||'';
    try{const r=await fetch(`/api/profile/${encodeURIComponent(profile.username||'alex')}`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify(profile)});if(r.status===401&&!token){const t=prompt('Admin token for server save (leave blank to keep this browser-only):');if(t){sessionStorage.setItem('zat-admin-token',t);return saveProfile()}}}catch{}
  }
  toast('Saved. Public profile and story cards are updated.');
}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),2600)}
async function track(type,meta={}){try{navigator.sendBeacon?.('/api/events',new Blob([JSON.stringify({type,meta,username:profile.username,ts:Date.now()})],{type:'application/json'}))}catch{}}
