/**
 * Alex Den's published content.
 *
 * This is the evidence layer. Each piece names the Items that appear in it,
 * which drives both directions of the relationship: "Everything in this video"
 * on a piece of content, and "Seen in" on an Item.
 */
import type { Content } from '@/lib/schema';

export const alexContent: Content[] = [
  {
    id: 'c_bag2026',
    personId: 'p_alex',
    slug: 'whats-in-my-camera-bag-2026',
    type: 'youtube',
    title: "What's actually in my camera bag — 2026",
    summary:
      'Everything that made it into the bag this year, what got cut, and the one piece I regret buying.',
    thumb: { key: 'spaces/photography', alt: 'Camera body and lens laid out', retina: true },
    url: 'https://example.com/watch/camera-bag-2026',
    publishedAt: '2026-02-11',
    itemIds: ['i_a7iv', 'i_sigma35', 'i_peakdesign', 'i_tripod', 'i_cfexpress'],
    views: 184_300,
  },
  {
    id: 'c_dolomites',
    personId: 'p_alex',
    slug: 'eight-days-in-the-dolomites',
    type: 'reel',
    title: 'Eight days in the Dolomites',
    summary: 'A short cut from the trip that changed how I shoot.',
    thumb: { key: 'spaces/memories', alt: 'Amber mountain range at sunrise', retina: true },
    url: 'https://example.com/watch/dolomites',
    publishedAt: '2025-06-30',
    itemIds: ['i_a7iv', 'i_sigma35', 'i_carryon', 'i_cubes'],
    views: 412_800,
  },
  {
    id: 'c_rereads',
    personId: 'p_alex',
    slug: 'five-books-i-actually-reread',
    type: 'article',
    title: 'The five books I actually re-read',
    summary:
      'Not a list of what impressed me. A list of what I have returned to, and what I got wrong about each one the first time.',
    thumb: { key: 'books/deep-work', alt: 'A stack of paperbacks', retina: false },
    url: 'https://example.com/read/five-books',
    publishedAt: '2026-01-06',
    itemIds: ['i_atomic', 'i_deepwork', 'i_almanack', 'i_thinking', 'i_stoic'],
    views: 58_900,
  },
  {
    id: 'c_desk',
    personId: 'p_alex',
    slug: 'desk-setup-honestly-reviewed',
    type: 'youtube',
    title: 'My desk setup, honestly reviewed',
    summary: 'Three years with the same four things, including what I would not buy again.',
    thumb: { key: 'spaces/work', alt: 'Laptop on a desk in low light', retina: true },
    url: 'https://example.com/watch/desk-setup',
    publishedAt: '2026-04-22',
    itemIds: ['i_laptop', 'i_keyboard', 'i_chair', 'i_notebook'],
    views: 226_100,
  },
  {
    id: 'c_knit',
    personId: 'p_alex',
    slug: 'one-knit-four-winters',
    type: 'reel',
    title: 'One knit, four winters',
    summary: 'What a £40 sweater looks like after four years of constant wear.',
    thumb: { key: 'spaces/wardrobe', alt: 'Folded burgundy knit sweater', retina: true },
    url: 'https://example.com/watch/one-knit',
    publishedAt: '2026-03-02',
    itemIds: ['i_knit', 'i_oxford', 'i_trousers', 'i_sneakers'],
    views: 631_400,
  },
  {
    id: 'c_listen',
    personId: 'p_alex',
    slug: 'what-i-listen-on',
    type: 'tiktok',
    title: 'What I actually listen on',
    summary: 'The £40 pair that beats the £300 pair, and when it does not.',
    thumb: { key: 'spaces/music', alt: 'Over-ear headphones in low light', retina: true },
    url: 'https://example.com/watch/what-i-listen-on',
    publishedAt: '2026-05-19',
    itemIds: ['i_headphones', 'i_iem', 'i_interface'],
    views: 298_700,
  },
  {
    id: 'c_carryon',
    personId: 'p_alex',
    slug: 'carry-on-only-two-weeks',
    type: 'reel',
    title: 'Two weeks, carry-on only',
    summary: 'The packing system I have not changed in two years.',
    thumb: { key: 'spaces/travel', alt: 'Mountain peaks through fog', retina: true },
    url: 'https://example.com/watch/carry-on-only',
    publishedAt: '2026-07-08',
    itemIds: ['i_carryon', 'i_cubes', 'i_adapter', 'i_knit'],
    views: 355_200,
  },
  {
    id: 'c_gym',
    personId: 'p_alex',
    slug: 'home-gym-in-a-shoebox',
    type: 'tiktok',
    title: 'A home gym in a shoebox',
    summary: 'Three items, four sessions a week, two years.',
    thumb: { key: 'spaces/fitness', alt: 'Matte black dumbbell', retina: true },
    url: 'https://example.com/watch/home-gym',
    publishedAt: '2026-08-14',
    itemIds: ['i_dumbbells', 'i_mat', 'i_runners'],
    views: 143_600,
  },
];
