/**
 * Items inside Alex Den's Spaces.
 *
 * Every entry carries the full trust payload — disclosure, duration of use,
 * frequency, likes, dislikes and alternatives. That is the point of Zat: a
 * recommendation without evidence is just an advert.
 *
 * Products are referred to by their real names, which is ordinary factual
 * reference. No brand logos or brand artwork are reproduced anywhere.
 */
import type { Item } from '@/lib/schema';

type Seed = Omit<Item, 'personId' | 'currency' | 'featured' | 'order'> &
  Partial<Pick<Item, 'currency' | 'featured' | 'order'>>;

const build = (seeds: Seed[]): Item[] =>
  seeds.map((s, i) => ({
    personId: 'p_alex',
    currency: 'GBP' as const,
    featured: s.featured ?? i === 0,
    order: s.order ?? i + 1,
    ...s,
  }));

export const alexItems: Item[] = build([
  // --- Photography --------------------------------------------------------
  {
    id: 'i_a7iv',
    spaceId: 's_photography',
    slug: 'sony-a7-iv',
    title: 'Sony A7 IV',
    brand: 'Sony',
    image: { key: 'spaces/photography', alt: 'Full-frame mirrorless camera body', retina: true },
    description:
      'A 33-megapixel full-frame mirrorless body. The middle option in the range, and the one most people should probably buy.',
    creatorNote:
      'Main camera since 2023 and the thing I would replace first if it were stolen. Used for almost every travel shoot on this profile. The autofocus is the reason — I can hand it to someone who has never used a camera and still get the shot. It is heavier than I expected and I notice it by hour six of walking.',
    price: 2099,
    retailer: 'Independent camera shop',
    productUrl: 'https://example.com/shop/sony-a7-iv',
    disclosure: 'purchased',
    usedSince: 'March 2023',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Autofocus that simply does not miss', 'Colour straight out of camera needs little work', 'Battery lasts a full shooting day'],
    dislikes: ['Heavier than the spec sheet suggests', 'Menu system still takes a minute to navigate'],
    alternatives: ['Sony A7C II if weight is your main concern', 'Fujifilm X-T5 for a lighter APS-C setup'],
    updatedAt: '2026-09-14',
  },
  {
    id: 'i_sigma35',
    spaceId: 's_photography',
    slug: 'sigma-35mm-f14',
    title: 'Sigma 35mm f/1.4 DG DN Art',
    brand: 'Sigma',
    image: { key: 'plinth/optics', alt: 'Prime lens on a dark studio plinth', retina: false },
    description: 'A fast 35mm prime for full-frame mirrorless bodies.',
    creatorNote:
      'If you are starting out, buy this before you upgrade the body. It stays on the camera roughly eight days in ten. Wide enough for a room, tight enough for a portrait, and it renders skin in a way I have not managed to replicate with a zoom.',
    price: 749,
    retailer: 'Independent camera shop',
    productUrl: 'https://example.com/shop/sigma-35mm',
    disclosure: 'affiliate',
    usedSince: 'May 2023',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Sharp wide open', 'Focus is quiet enough for video', 'Built like it will outlive the body'],
    dislikes: ['Front element picks up flare against strong backlight'],
    alternatives: ['Sony 35mm f/1.8 for half the weight and most of the result'],
    updatedAt: '2026-09-14',
  },
  {
    id: 'i_peakdesign',
    spaceId: 's_photography',
    slug: 'everyday-backpack-30l',
    title: 'Everyday Backpack 30L',
    brand: 'Peak Design',
    image: { key: 'plinth/field', alt: 'Camera backpack standing in soft light', retina: false },
    description: 'A camera backpack with reconfigurable internal dividers and side access.',
    creatorNote:
      'Three years of airports and it still closes properly. The side access matters more than I thought — being able to pull the body out without putting the bag down has saved shots. It is expensive and I hesitated for a long time.',
    price: 289,
    retailer: 'Peak Design',
    productUrl: 'https://example.com/shop/everyday-backpack',
    disclosure: 'purchased',
    usedSince: 'January 2023',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Side access is genuinely faster', 'Dividers hold their shape after years'],
    dislikes: ['Heavy before you put anything in it', 'Price is hard to justify to anyone else'],
    alternatives: ['Wandrd PRVKE 31 for a similar layout at less cost'],
    updatedAt: '2026-08-27',
  },
  {
    id: 'i_tripod',
    spaceId: 's_photography',
    slug: 'travel-tripod',
    title: 'Carbon travel tripod',
    brand: 'SmallRig',
    image: { key: 'plinth/studio', alt: 'Folded carbon tripod', retina: false },
    description: 'A compact carbon-fibre tripod that folds to roughly the length of a forearm.',
    creatorNote:
      'Bought for long exposures on the Dolomites trip. Honest assessment: I use it far less than I imagined, maybe once a trip. It is good, but be realistic about whether you will carry it.',
    price: 179,
    retailer: 'SmallRig',
    productUrl: 'https://example.com/shop/travel-tripod',
    disclosure: 'purchased',
    usedSince: 'August 2023',
    frequency: 'occasionally',
    wouldBuyAgain: false,
    likes: ['Folds genuinely small', 'Ball head holds a heavy body without creep'],
    dislikes: ['I do not carry it often enough to justify it', 'Leg locks need a firm hand in cold weather'],
    alternatives: ['A tabletop tripod covers most of what I actually use this for'],
    updatedAt: '2026-07-30',
  },
  {
    id: 'i_cfexpress',
    spaceId: 's_photography',
    slug: 'cfexpress-type-a',
    title: 'CFexpress Type A 160GB',
    brand: 'SanDisk',
    image: { key: 'plinth/optics', alt: 'Memory card on a dark surface', retina: false },
    description: 'High-speed memory card for sustained burst and 4K capture.',
    creatorNote:
      'Not interesting, but it is the difference between the buffer clearing and missing the next frame. I carry three and format them at the start of every trip, never at the end.',
    price: 219,
    retailer: 'Independent camera shop',
    productUrl: 'https://example.com/shop/cfexpress-a',
    disclosure: 'purchased',
    usedSince: 'March 2023',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Buffer clears fast enough to stop thinking about it'],
    dislikes: ['Absurdly expensive per gigabyte'],
    alternatives: ['A fast SD card is fine unless you shoot long bursts'],
    updatedAt: '2026-06-11',
  },

  // --- Wardrobe -----------------------------------------------------------
  {
    id: 'i_knit',
    spaceId: 's_wardrobe',
    slug: 'merino-crewneck',
    title: 'Merino crewneck in burgundy',
    brand: 'Uniqlo',
    image: { key: 'spaces/wardrobe', alt: 'Folded burgundy merino crewneck', retina: true },
    description: 'A fine-gauge extra-fine merino crewneck.',
    creatorNote:
      'The single most-worn thing I own. Four winters, washed cold, still holds its shape at the cuffs. I bought a second in the same colour because I could not find anything better at ten times the price.',
    price: 39.9,
    retailer: 'Uniqlo',
    productUrl: 'https://example.com/shop/merino-crewneck',
    disclosure: 'purchased',
    usedSince: 'October 2022',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Holds shape after repeated washing', 'Layers under a jacket without bulk', 'Costs a fraction of the alternatives'],
    dislikes: ['Pills slightly under a backpack strap'],
    alternatives: ['John Smedley if you want it to last a decade rather than four years'],
    updatedAt: '2026-09-02',
  },
  {
    id: 'i_oxford',
    spaceId: 's_wardrobe',
    slug: 'oxford-shirt',
    title: 'Oxford cloth button-down',
    brand: 'Kamakura',
    image: { key: 'plinth/studio', alt: 'White oxford shirt, folded', retina: false },
    description: 'A classic oxford-weave cotton shirt with a soft roll collar.',
    creatorNote:
      'Worn under almost every knit on this profile. The collar sits properly without a tie, which is the whole reason to buy a good one. Needs ironing and I have made peace with that.',
    price: 95,
    retailer: 'Kamakura Shirts',
    productUrl: 'https://example.com/shop/oxford-shirt',
    disclosure: 'purchased',
    usedSince: 'February 2023',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Collar rolls correctly with no tie', 'Fabric softens rather than wearing out'],
    dislikes: ['Creases the moment you sit down'],
    alternatives: ['Uniqlo oxford at a quarter of the price if you are not fussy about the collar'],
    updatedAt: '2026-08-18',
  },
  {
    id: 'i_trousers',
    spaceId: 's_wardrobe',
    slug: 'wool-trousers',
    title: 'Charcoal wool trousers',
    brand: 'Studio Nicholson',
    image: { key: 'plinth/studio', alt: 'Charcoal tailored trousers', retina: false },
    description: 'A wide, high-rise wool trouser with a clean front.',
    creatorNote:
      'Gifted by a friend who works at the shop, and I have declared that below. They changed how I dress — I had not realised how much a proper trouser break matters. Expensive enough that I would have hesitated buying them myself.',
    price: 320,
    retailer: 'Studio Nicholson',
    productUrl: 'https://example.com/shop/wool-trousers',
    disclosure: 'gifted',
    usedSince: 'November 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Drape is worth the money', 'Wears cool in summer despite being wool'],
    dislikes: ['Dry clean only', 'Wide leg is not for everyone'],
    alternatives: ['COS has a similar cut at a third of the price'],
    updatedAt: '2026-07-22',
  },
  {
    id: 'i_sneakers',
    spaceId: 's_wardrobe',
    slug: 'leather-sneakers',
    title: 'Minimal leather sneakers',
    brand: 'Common Projects',
    image: { key: 'plinth/field', alt: 'White leather sneakers', retina: false },
    description: 'A plain white leather sneaker with a thin rubber sole.',
    creatorNote:
      'Two years in and they have creased in the way leather should. I resole rather than replace. If you want the look for less, the alternative below is genuinely close.',
    price: 350,
    retailer: 'Mr Porter',
    productUrl: 'https://example.com/shop/leather-sneakers',
    disclosure: 'affiliate',
    usedSince: 'April 2024',
    frequency: 'daily',
    wouldBuyAgain: false,
    likes: ['Ages well rather than looking worn', 'Goes with everything else in this Space'],
    dislikes: ['The price is difficult to defend', 'No grip at all in the wet'],
    alternatives: ['Oliver Cabell Low 1 for roughly a third of the cost'],
    updatedAt: '2026-09-02',
  },
  {
    id: 'i_watch',
    spaceId: 's_wardrobe',
    slug: 'field-watch',
    title: 'Field watch, 36mm',
    brand: 'Seiko',
    image: { key: 'plinth/optics', alt: 'Small field watch on a leather strap', retina: false },
    description: 'A compact mechanical field watch on a leather strap.',
    creatorNote:
      'Small enough to disappear under a cuff. I wear it every day and have never once needed a smartwatch feature badly enough to switch back.',
    price: 240,
    retailer: 'Seiko Boutique',
    productUrl: 'https://example.com/shop/field-watch',
    disclosure: 'purchased',
    usedSince: 'June 2022',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['36mm suits most wrists better than the trend suggests', 'Mechanical means no charging'],
    dislikes: ['Loses about 15 seconds a day'],
    alternatives: ['Hamilton Khaki Field Mechanical'],
    updatedAt: '2026-05-04',
  },

  // --- Work ---------------------------------------------------------------
  {
    id: 'i_laptop',
    spaceId: 's_work',
    slug: 'laptop-14',
    title: '14-inch laptop, 32GB',
    brand: null,
    image: { key: 'spaces/work', alt: 'Laptop closed on a desk in low light', retina: true },
    description: 'A 14-inch workstation laptop with 32GB of memory.',
    creatorNote:
      'Design files, raw photo libraries and a browser I refuse to tidy. The 32GB is the part that matters; I ran out constantly on 16. Three years old and I have no reason to replace it.',
    price: 2399,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/laptop-14',
    disclosure: 'purchased',
    usedSince: 'September 2023',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Silent under sustained load', 'Screen is accurate enough to grade photos on'],
    dislikes: ['Ports still require an adapter for card readers'],
    alternatives: ['The previous generation is markedly cheaper and nearly as quick'],
    updatedAt: '2026-09-05',
  },
  {
    id: 'i_keyboard',
    spaceId: 's_work',
    slug: 'low-profile-keyboard',
    title: 'Low-profile mechanical keyboard',
    brand: 'Keychron',
    image: { key: 'plinth/studio', alt: 'Low-profile mechanical keyboard', retina: false },
    description: 'A 75% layout mechanical keyboard with low-profile switches.',
    creatorNote:
      'Quieter than it looks, which matters in a shared studio. I switched to low-profile after a wrist problem and have not gone back.',
    price: 129,
    retailer: 'Keychron',
    productUrl: 'https://example.com/shop/low-profile-keyboard',
    disclosure: 'purchased',
    usedSince: 'February 2024',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Low profile is genuinely kinder on the wrist', 'Battery measured in weeks'],
    dislikes: ['Software for remapping is poor'],
    alternatives: ['Logitech MX Mechanical Mini'],
    updatedAt: '2026-08-12',
  },
  {
    id: 'i_chair',
    spaceId: 's_work',
    slug: 'task-chair',
    title: 'Second-hand task chair',
    brand: 'Herman Miller',
    image: { key: 'plinth/field', alt: 'Mesh-backed task chair', retina: false },
    description: 'A mesh-back ergonomic task chair, bought refurbished.',
    creatorNote:
      'Bought refurbished for less than half retail and it is the best money I have spent on the studio. Buy second-hand — these last twenty years and the refurbished market is excellent.',
    price: 540,
    retailer: 'Refurbished office supplier',
    productUrl: 'https://example.com/shop/task-chair',
    disclosure: 'purchased',
    usedSince: 'July 2022',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Refurbished price makes it sensible', 'Still adjusts smoothly after four years'],
    dislikes: ['Takes a week to find the right settings'],
    alternatives: ['Any refurbished Aeron or Embody from a reputable seller'],
    updatedAt: '2026-04-20',
  },
  {
    id: 'i_notebook',
    spaceId: 's_work',
    slug: 'dot-grid-notebook',
    title: 'A5 dot-grid notebook',
    brand: 'Leuchtturm1917',
    image: { key: 'plinth/studio', alt: 'Closed A5 notebook', retina: false },
    description: 'A hardback A5 notebook with numbered dot-grid pages.',
    creatorNote:
      'Every project starts here before it touches a screen. Numbered pages and an index are the only features that matter.',
    price: 22,
    retailer: 'Local stationer',
    productUrl: 'https://example.com/shop/dot-grid-notebook',
    disclosure: 'purchased',
    usedSince: 'Since 2019',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Numbered pages plus an index', 'Lies flat without cracking the spine'],
    dislikes: ['Paper is thin for fountain pens'],
    alternatives: ['Midori MD if you write with ink'],
    updatedAt: '2026-03-15',
  },
  {
    id: 'i_display',
    spaceId: 's_work',
    slug: 'colour-accurate-display',
    title: '27-inch 4K display',
    brand: 'Dell',
    image: { key: 'plinth/studio', alt: 'Slim-bezel desktop monitor in low light', retina: false },
    description: 'A 27-inch 4K IPS monitor with a single-cable dock built in.',
    creatorNote:
      'Bought for colour rather than resolution. It comes close enough to the laptop screen that a photo graded on one looks right on the other, which was the whole point. The built-in dock means one cable to the desk, and that single detail has done more for my desk than anything else in this Space.',
    price: 549,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/4k-display',
    disclosure: 'purchased',
    usedSince: 'November 2023',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Matches the laptop panel closely enough to trust', 'One cable carries video, data and power'],
    dislikes: ['Stand takes up more desk than it should', 'The coating softens fine text slightly'],
    alternatives: ['A 27-inch 1440p panel if you are not grading photographs'],
    updatedAt: '2026-09-05',
  },

  // --- Books --------------------------------------------------------------
  {
    id: 'i_atomic',
    spaceId: 's_books',
    slug: 'atomic-habits',
    title: 'Atomic Habits',
    brand: 'James Clear',
    image: { key: 'books/atomic-habits', alt: 'Cover of Atomic Habits', retina: false },
    description: 'A practical book on building small habits that compound.',
    creatorNote:
      'The one that actually changed a behaviour rather than just describing one. The chapter on environment design is the part I still use. The rest is longer than it needs to be.',
    price: 10.99,
    retailer: 'Local bookshop',
    productUrl: 'https://example.com/shop/atomic-habits',
    disclosure: 'purchased',
    usedSince: '2021',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Environment design chapter is genuinely useful', 'Short chapters make it easy to return to'],
    dislikes: ['Could have been half the length'],
    alternatives: ['Tiny Habits by BJ Fogg covers similar ground more briefly'],
    updatedAt: '2026-09-11',
  },
  {
    id: 'i_deepwork',
    spaceId: 's_books',
    slug: 'deep-work',
    title: 'Deep Work',
    brand: 'Cal Newport',
    image: { key: 'books/deep-work', alt: 'Cover of Deep Work', retina: false },
    description: 'An argument for sustained, undistracted concentration.',
    creatorNote:
      'I read this every January. It is prescriptive to the point of being irritating, and I still restructure my week around it each year.',
    price: 9.99,
    retailer: 'Local bookshop',
    productUrl: 'https://example.com/shop/deep-work',
    disclosure: 'purchased',
    usedSince: '2020',
    frequency: 'seasonally',
    wouldBuyAgain: true,
    likes: ['Changed how I schedule mornings'],
    dislikes: ['Assumes a degree of control over your calendar that many people do not have'],
    alternatives: ['Four Thousand Weeks for a gentler take on the same problem'],
    updatedAt: '2026-09-11',
  },
  {
    id: 'i_almanack',
    spaceId: 's_books',
    slug: 'almanack-naval-ravikant',
    title: 'The Almanack of Naval Ravikant',
    brand: 'Eric Jorgenson',
    image: { key: 'books/almanack', alt: 'Cover of The Almanack of Naval Ravikant', retina: false },
    description: 'A collected edition of essays and interviews on wealth and judgement.',
    creatorNote:
      'Better dipped into than read straight through. I disagree with a reasonable amount of it, which is partly why it stays on the shelf.',
    price: 0,
    retailer: 'Free online',
    productUrl: 'https://example.com/shop/almanack',
    disclosure: 'editorial',
    usedSince: '2022',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Available free, legitimately', 'Rewards skimming'],
    dislikes: ['Repetitive when read end to end'],
    alternatives: [],
    updatedAt: '2026-09-11',
  },
  {
    id: 'i_thinking',
    spaceId: 's_books',
    slug: 'thinking-fast-and-slow',
    title: 'Thinking, Fast and Slow',
    brand: 'Daniel Kahneman',
    image: { key: 'books/thinking-fast-slow', alt: 'Cover of Thinking, Fast and Slow', retina: false },
    description: 'A survey of the two systems behind human judgement.',
    creatorNote:
      'Hard going and worth it. Some of the priming research has not replicated well, which is worth knowing before you quote it at people.',
    price: 12.99,
    retailer: 'Local bookshop',
    productUrl: 'https://example.com/shop/thinking-fast-slow',
    disclosure: 'purchased',
    usedSince: '2019',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Reframed how I think about my own certainty'],
    dislikes: ['Dense', 'Parts of the underlying research are contested'],
    alternatives: ['The Undoing Project for the story behind it'],
    updatedAt: '2026-09-11',
  },
  {
    id: 'i_stoic',
    spaceId: 's_books',
    slug: 'the-daily-stoic',
    title: 'The Daily Stoic',
    brand: 'Ryan Holiday',
    image: { key: 'books/daily-stoic', alt: 'Cover of The Daily Stoic', retina: false },
    description: 'A page of stoic philosophy for each day of the year.',
    creatorNote:
      'A page a morning. The format does most of the work — I would not have finished it as a continuous book.',
    price: 14.99,
    retailer: 'Local bookshop',
    productUrl: 'https://example.com/shop/daily-stoic',
    disclosure: 'affiliate',
    usedSince: '2023',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['The daily format is the feature'],
    dislikes: ['Some entries stretch to fill the page'],
    alternatives: ['Meditations, unabridged, if you want the source'],
    updatedAt: '2026-09-11',
  },

  // --- Music --------------------------------------------------------------
  {
    id: 'i_headphones',
    spaceId: 's_music',
    slug: 'noise-cancelling-headphones',
    title: 'WH-1000XM5',
    brand: 'Sony',
    image: { key: 'spaces/music', alt: 'Matte black over-ear headphones', retina: true },
    description: 'Over-ear wireless headphones with adaptive noise cancellation.',
    creatorNote:
      'On my head for most of the working day and every flight. The noise cancelling is the reason I can work in a cafe at all. I wish they folded like the previous generation.',
    price: 299,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/wh-1000xm5',
    disclosure: 'affiliate',
    usedSince: 'June 2023',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Noise cancelling is still class-leading', 'Comfortable across a long flight', 'Call quality is finally good'],
    dislikes: ['No longer folds flat', 'Case is larger than it needs to be'],
    alternatives: ['Bose QuietComfort Ultra if comfort matters more than sound'],
    updatedAt: '2026-08-21',
  },
  {
    id: 'i_iem',
    spaceId: 's_music',
    slug: 'wired-iems',
    title: 'Wired in-ear monitors',
    brand: 'Moondrop',
    image: { key: 'plinth/audio', alt: 'Wired in-ear monitors', retina: false },
    description: 'A single dynamic-driver in-ear monitor with a detachable cable.',
    creatorNote:
      'What I actually listen critically on. Forty pounds and they embarrass things costing ten times more. No battery, no pairing, no firmware.',
    price: 42,
    retailer: 'Specialist audio shop',
    productUrl: 'https://example.com/shop/wired-iems',
    disclosure: 'purchased',
    usedSince: 'January 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Absurd value', 'Detachable cable means they are repairable'],
    dislikes: ['Cable is microphonic when walking'],
    alternatives: ['Truthear Hexa'],
    updatedAt: '2026-08-21',
  },
  {
    id: 'i_interface',
    spaceId: 's_music',
    slug: 'audio-interface',
    title: 'Two-channel audio interface',
    brand: 'Universal Audio',
    image: { key: 'plinth/audio', alt: 'Desktop audio interface', retina: false },
    description: 'A two-input desktop interface with onboard processing.',
    creatorNote:
      'Sent by the brand for a video I made last year, which is why it is labelled sponsored. I kept using it, which is the only endorsement I can honestly give.',
    price: 329,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/audio-interface',
    disclosure: 'sponsored',
    usedSince: 'October 2025',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Preamps are clean at high gain', 'Onboard processing saves a plugin chain'],
    dislikes: ['Needs its own software running', 'Overkill for voice recording alone'],
    alternatives: ['Focusrite Scarlett 2i2 covers most needs for a third of the price'],
    updatedAt: '2026-08-21',
  },
  {
    id: 'i_monitors',
    spaceId: 's_music',
    slug: 'nearfield-monitors',
    title: 'Nearfield studio monitors',
    brand: 'Kali Audio',
    image: { key: 'plinth/audio', alt: 'Pair of nearfield studio monitors', retina: false },
    description: 'A pair of powered six-inch nearfield monitors with boundary compensation.',
    creatorNote:
      'The first speakers I owned that told me the truth rather than what I wanted to hear. Mixes made on these translate to a car and to a phone, which is the only test that counts. Read the boundary settings on the back before you put them against a wall — I ignored them for a month and wondered why everything sounded thick.',
    price: 398,
    retailer: 'Specialist audio shop',
    productUrl: 'https://example.com/shop/nearfield-monitors',
    disclosure: 'purchased',
    usedSince: 'February 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Honest rather than flattering', 'Boundary switches actually fix a bad room', 'Quiet at idle'],
    dislikes: ['They expose a bad recording immediately', 'Too large for a small desk'],
    alternatives: ['Kali LP-6 in the five-inch size if your desk is shallow'],
    updatedAt: '2026-08-21',
  },
  {
    id: 'i_recorder',
    spaceId: 's_music',
    slug: 'field-recorder',
    title: 'Portable field recorder',
    brand: 'Zoom',
    image: { key: 'plinth/field', alt: 'Handheld field recorder', retina: false },
    description: 'A handheld multi-track recorder with interchangeable capsules and two XLR inputs.',
    creatorNote:
      'Carried on every trip since the Dolomites. Half the audio under the videos on this profile is room tone and weather recorded on this rather than anything from a camera. It eats batteries, so it lives in the bag with a spare set taped to it.',
    price: 249,
    retailer: 'Specialist audio shop',
    productUrl: 'https://example.com/shop/field-recorder',
    disclosure: 'affiliate',
    usedSince: 'June 2023',
    frequency: 'monthly',
    wouldBuyAgain: true,
    likes: ['Two XLR inputs mean it doubles as an interface', 'Records for hours on ordinary AA cells'],
    dislikes: ['Goes through batteries quickly', 'The plastic body feels cheaper than the price'],
    alternatives: ['Zoom H1essential if you only need the built-in microphones'],
    updatedAt: '2026-08-21',
  },

  // --- Travel -------------------------------------------------------------
  {
    id: 'i_carryon',
    spaceId: 's_travel',
    slug: 'carry-on-case',
    title: 'Aluminium carry-on',
    brand: 'Rimowa',
    image: { key: 'plinth/field', alt: 'Aluminium carry-on case', retina: false },
    description: 'A four-wheel aluminium cabin case.',
    creatorNote:
      'Dented in a way I have grown to like. Heavy when empty, which costs you on strict weight limits — worth knowing before you buy.',
    price: 1050,
    retailer: 'Rimowa',
    productUrl: 'https://example.com/shop/carry-on',
    disclosure: 'purchased',
    usedSince: 'April 2022',
    frequency: 'monthly',
    wouldBuyAgain: false,
    likes: ['Will outlive me', 'Wheels are still silent after four years'],
    dislikes: ['Heavy before packing', 'Marks immediately, which you must be fine with'],
    alternatives: ['Away Bigger Carry-On at a fifth of the price'],
    updatedAt: '2026-09-09',
  },
  {
    id: 'i_cubes',
    spaceId: 's_travel',
    slug: 'packing-cubes',
    title: 'Compression packing cubes',
    brand: 'Peak Design',
    image: { key: 'plinth/field', alt: 'Set of packing cubes', retina: false },
    description: 'Zip-compression fabric cubes for organising a case.',
    creatorNote:
      'The least interesting thing on this profile and one of the most useful. Two weeks of clothing into a carry-on.',
    price: 59,
    retailer: 'Peak Design',
    productUrl: 'https://example.com/shop/packing-cubes',
    disclosure: 'affiliate',
    usedSince: 'April 2023',
    frequency: 'monthly',
    wouldBuyAgain: true,
    likes: ['Compression actually works', 'Survives being over-stuffed'],
    dislikes: ['Adds a little weight of its own'],
    alternatives: ['Any compression cube set will do most of this'],
    updatedAt: '2026-09-09',
  },
  {
    id: 'i_adapter',
    spaceId: 's_travel',
    slug: 'travel-adapter',
    title: 'GaN travel charger, 65W',
    brand: 'Anker',
    image: { key: 'plinth/studio', alt: 'Compact travel charger', retina: false },
    description: 'A compact multi-port charger with international plugs.',
    creatorNote:
      'One charger for laptop, camera and phone. Replaced four things in the bag with one.',
    price: 55,
    retailer: 'Anker',
    productUrl: 'https://example.com/shop/travel-charger',
    disclosure: 'purchased',
    usedSince: 'February 2024',
    frequency: 'monthly',
    wouldBuyAgain: true,
    likes: ['Charges the laptop at full speed', 'Replaced several separate bricks'],
    dislikes: ['Runs warm under full load'],
    alternatives: ['UGREEN Nexode 65W'],
    updatedAt: '2026-09-09',
  },
  {
    id: 'i_flightsocks',
    spaceId: 's_travel',
    slug: 'compression-flight-socks',
    title: 'Compression flight socks',
    brand: null,
    image: { key: 'detail/knit-weave', alt: 'Close detail of a fine knit', retina: false },
    description: 'Graduated-compression knee socks rated for long-haul sitting.',
    creatorNote:
      'Eighteen pounds and the single least glamorous thing on this profile. I arrive off a twelve-hour flight without the swollen ankles I used to accept as part of travelling. They are a genuine effort to get on and I put them on anyway, every time.',
    price: 18,
    retailer: 'Pharmacy',
    productUrl: 'https://example.com/shop/compression-socks',
    disclosure: 'purchased',
    usedSince: 'February 2023',
    frequency: 'monthly',
    wouldBuyAgain: true,
    likes: ['The difference after a long flight is obvious', 'Cheap enough to own several pairs'],
    dislikes: ['Genuinely hard to put on', 'They look exactly as unglamorous as they sound'],
    alternatives: ['Getting up and walking every hour, which works and which I never do'],
    updatedAt: '2026-09-09',
  },
  {
    id: 'i_downjacket',
    spaceId: 's_travel',
    slug: 'packable-down-jacket',
    title: 'Packable down jacket',
    brand: 'Montbell',
    image: { key: 'scenes/cold-summit', alt: 'Cold mountain summit under thin light', retina: true },
    description: 'An ultralight hooded down jacket that compresses into its own pocket.',
    creatorNote:
      'Packs to the size of a grapefruit and has been the difference between a good evening and a cold one on every trip since 2022. It is not waterproof and pretending otherwise gets you wet — it goes under a shell when the weather turns.',
    price: 285,
    retailer: 'Outdoor specialist',
    productUrl: 'https://example.com/shop/packable-down-jacket',
    disclosure: 'purchased',
    usedSince: 'October 2022',
    frequency: 'seasonally',
    wouldBuyAgain: true,
    likes: ['Compresses smaller than any other jacket I have owned', 'Warm out of all proportion to its weight'],
    dislikes: ['The fabric snags on anything sharp', 'Useless in rain without a shell over it'],
    alternatives: ['A synthetic-fill jacket if you are often wet — it keeps working when down gives up'],
    updatedAt: '2026-09-09',
  },

  // --- Fitness ------------------------------------------------------------
  {
    id: 'i_dumbbells',
    spaceId: 's_fitness',
    slug: 'adjustable-dumbbells',
    title: 'Adjustable dumbbells',
    brand: 'Bowflex',
    image: { key: 'spaces/fitness', alt: 'Matte black dumbbell', retina: true },
    description: 'A pair of dial-adjustable dumbbells replacing a full rack.',
    creatorNote:
      'The entire home gym in the space of a shoebox. Four sessions a week for two years. The adjustment dial is a wear point — treat it gently.',
    price: 429,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/adjustable-dumbbells',
    disclosure: 'purchased',
    usedSince: 'January 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Replaces an entire rack', 'Adjustment is quick between sets'],
    dislikes: ['Bulky shape is awkward for some movements', 'Dial mechanism feels fragile'],
    alternatives: ['A fixed set if you have the floor space — they never break'],
    updatedAt: '2026-08-30',
  },
  {
    id: 'i_runners',
    spaceId: 's_fitness',
    slug: 'running-shoes',
    title: 'Daily trainer running shoes',
    brand: 'ASICS',
    image: { key: 'plinth/field', alt: 'Running shoes', retina: false },
    description: 'A cushioned neutral daily trainer.',
    creatorNote:
      'Third consecutive pair of the same model. When something works, I stop experimenting. About 700km before the midsole goes flat.',
    price: 145,
    retailer: 'Local running shop',
    productUrl: 'https://example.com/shop/running-shoes',
    disclosure: 'purchased',
    usedSince: 'Since 2022',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Predictable across the whole life of the shoe', 'Wide enough at the toe box'],
    dislikes: ['Upper wears through before the sole does'],
    alternatives: ['Get fitted at a running shop rather than copying anyone else'],
    updatedAt: '2026-08-30',
  },
  {
    id: 'i_mat',
    spaceId: 's_fitness',
    slug: 'exercise-mat',
    title: 'Dense foam mat',
    brand: null,
    image: { key: 'plinth/field', alt: 'Rolled exercise mat', retina: false },
    description: 'A high-density mat for floor work.',
    creatorNote: 'Twenty pounds, four years, no complaints. Buy the thick one.',
    price: 24,
    retailer: 'Local sports shop',
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2022',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Thick enough for kneeling work'],
    dislikes: ['Smells for the first fortnight'],
    alternatives: [],
    updatedAt: '2026-08-30',
  },
  {
    id: 'i_strap',
    spaceId: 's_fitness',
    slug: 'heart-rate-strap',
    title: 'Heart-rate chest strap',
    brand: 'Polar',
    image: { key: 'plinth/studio', alt: 'Chest-strap heart rate sensor', retina: false },
    description: 'A chest-worn ECG heart-rate sensor that pairs over Bluetooth and ANT+.',
    creatorNote:
      'I bought this because my watch kept telling me an easy run was a hard one. The strap disagreed, and the strap was right. Two years of steady training decisions rest on it. Wet the contacts before you put it on or the first five minutes are nonsense.',
    price: 79,
    retailer: 'Local running shop',
    productUrl: 'https://example.com/shop/heart-rate-strap',
    disclosure: 'purchased',
    usedSince: 'April 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Accurate in a way a wrist sensor is not', 'Pairs with a watch and a phone at the same time'],
    dislikes: ['Needs wetting before every session', 'The strap itself wears out yearly'],
    alternatives: ['An armband sensor if you cannot stand a chest strap'],
    updatedAt: '2026-08-30',
  },
  {
    id: 'i_pullupbar',
    spaceId: 's_fitness',
    slug: 'doorway-pull-up-bar',
    title: 'Doorway pull-up bar',
    brand: null,
    image: { key: 'detail/weight-end', alt: 'Close detail of a knurled steel bar end', retina: false },
    description: 'A leverage-mounted bar that fits a standard door frame without fixings.',
    creatorNote:
      'Thirty pounds and it turned a corridor into the most-used piece of equipment in the flat, simply because it is in the way. Check your door frame is sound before you trust it with your whole weight, and check it again every few months.',
    price: 32,
    retailer: 'Local sports shop',
    productUrl: 'https://example.com/shop/pull-up-bar',
    disclosure: 'purchased',
    usedSince: 'January 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Being in the way is the whole point', 'No drilling, no fixings'],
    dislikes: ['Marks the door frame', 'Only as safe as the frame it leans on'],
    alternatives: ['A free-standing frame if you have the floor space and a landlord'],
    updatedAt: '2026-08-30',
  },

  // --- Gaming, Movies, Ideas, Life, Memories ------------------------------
  {
    id: 'i_controller',
    spaceId: 's_gaming',
    slug: 'wireless-controller',
    title: 'Wireless controller',
    brand: null,
    image: { key: 'spaces/gaming', alt: 'Black wireless game controller', retina: true },
    description: 'A standard wireless gamepad with haptic triggers.',
    creatorNote: 'Nothing exotic. The haptics are genuinely good and the battery is genuinely not.',
    price: 64,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/controller',
    disclosure: 'purchased',
    usedSince: '2023',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['Haptics add more than expected'],
    dislikes: ['Battery life is poor'],
    alternatives: [],
    updatedAt: '2026-07-19',
  },
  {
    id: 'i_outerwilds',
    spaceId: 's_gaming',
    slug: 'outer-wilds',
    title: 'Outer Wilds',
    brand: 'Mobius Digital',
    image: { key: 'aura/ink', alt: 'Abstract cosmic artwork', retina: false },
    description: 'An exploration game built around a twenty-two minute time loop.',
    creatorNote:
      'The only game I wish I could forget in order to play again. Go in knowing nothing. Do not read anything else about it.',
    price: 22,
    retailer: 'Digital store',
    productUrl: 'https://example.com/shop/outer-wilds',
    disclosure: 'editorial',
    usedSince: '2024',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Nothing else structures discovery this well'],
    dislikes: ['The time loop frustrates some people early'],
    alternatives: [],
    updatedAt: '2026-07-19',
  },
  {
    id: 'i_handheld',
    spaceId: 's_gaming',
    slug: 'handheld-pc',
    title: 'Handheld gaming PC',
    brand: 'Valve',
    image: { key: 'plinth/studio', alt: 'Handheld gaming computer resting on a plinth', retina: false },
    description: 'A handheld Linux-based PC with a 7.4-inch OLED screen.',
    creatorNote:
      'It did the thing I did not expect: it made me finish games instead of collecting them. Forty minutes on a train is enough, and forty minutes was never enough when it meant sitting at a desk. The battery claim assumes you play something undemanding.',
    price: 569,
    retailer: 'Direct',
    productUrl: 'https://example.com/shop/handheld-pc',
    disclosure: 'purchased',
    usedSince: 'February 2024',
    frequency: 'weekly',
    wouldBuyAgain: true,
    likes: ['The OLED panel is the upgrade that matters', 'Sleep and resume actually works'],
    dislikes: ['Battery life depends entirely on what you run', 'Heavy after an hour in the hands'],
    alternatives: ['A Nintendo Switch if you mostly want the first-party games'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'i_hollowknight',
    spaceId: 's_gaming',
    slug: 'hollow-knight',
    title: 'Hollow Knight',
    brand: 'Team Cherry',
    image: { key: 'aura/moss', alt: 'Deep green abstract light field', retina: false },
    description: 'A hand-drawn side-scrolling game set in a ruined underground kingdom.',
    creatorNote:
      'Fifteen pounds and about seventy hours, which makes it the best value of anything on this profile by a distance. It explains almost nothing and trusts you to work it out, and that trust is the reason it stays with people. It is also genuinely hard, and I stopped twice before it clicked.',
    price: 14.99,
    retailer: 'Digital store',
    productUrl: 'https://example.com/shop/hollow-knight',
    disclosure: 'editorial',
    usedSince: '2022',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Enormous for the price', 'The map system makes getting lost feel deliberate'],
    dislikes: ['The difficulty loses people in the first three hours'],
    alternatives: ['Ori and the Will of the Wisps if you want the same shape with a gentler slope'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'i_obradinn',
    spaceId: 's_gaming',
    slug: 'return-of-the-obra-dinn',
    title: 'Return of the Obra Dinn',
    brand: 'Lucas Pope',
    image: { key: 'aura/plum', alt: 'Dark plum-toned abstract field', retina: false },
    description: 'A deduction game about identifying the crew of a ship that returned empty.',
    creatorNote:
      'The rare puzzle game that never tells you the answer and never needs to. You write the solution down on paper beside you, which no game had made me do since I was twelve. One playthrough only — there is nothing left once you know.',
    price: 17.99,
    retailer: 'Digital store',
    productUrl: 'https://example.com/shop/return-of-the-obra-dinn',
    disclosure: 'editorial',
    usedSince: '2023',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Deduction that is genuinely yours rather than guided', 'The one-bit art is legible and strange at once'],
    dislikes: ['The visual style causes some people motion sickness', 'No second playthrough'],
    alternatives: ['Outer Wilds, elsewhere in this Space, for the same feeling in a different shape'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'i_arrival',
    spaceId: 's_movies',
    slug: 'arrival',
    title: 'Arrival',
    brand: 'Denis Villeneuve',
    image: { key: 'spaces/movies', alt: 'Figure silhouetted against amber haze', retina: true },
    description: 'A first-contact film concerned with language and time.',
    creatorNote:
      'Watched five times. It rewards the rewatch more than almost anything else I own, because you spend the second viewing noticing what the first one hid.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2017',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Sound design', 'The structure only makes sense in retrospect'],
    dislikes: ['The subplot with the military is the weakest part'],
    alternatives: ['Story of Your Life, the Ted Chiang novella it came from'],
    updatedAt: '2026-05-28',
  },
  {
    id: 'i_bladerunner',
    spaceId: 's_movies',
    slug: 'blade-runner-2049',
    title: 'Blade Runner 2049',
    brand: 'Denis Villeneuve',
    image: { key: 'aura/ember', alt: 'Amber and ember toned abstract field', retina: false },
    description: 'A sequel concerned with memory and what counts as a life.',
    creatorNote: 'I put this on for the photography as often as for the story. Long, and it should be.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2018',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Every frame is composed', 'Score is extraordinary'],
    dislikes: ['Pacing loses some people entirely'],
    alternatives: [],
    updatedAt: '2026-05-28',
  },
  {
    id: 'i_pastlives',
    spaceId: 's_movies',
    slug: 'past-lives',
    title: 'Past Lives',
    brand: 'Celine Song',
    image: { key: 'scenes/night-glass', alt: 'City lights refracted through dark glass', retina: true },
    description: 'A film about two childhood friends meeting again across twenty-four years.',
    creatorNote:
      'The film I have recommended most in the last two years and the one I am least able to explain. Almost nothing happens and I have not stopped thinking about the last ten minutes. Watch it without reading about it first.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2023',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Restraint where another film would push', 'The final scene is held exactly long enough'],
    dislikes: ['If you need plot, there is not much here'],
    alternatives: ['Before Sunset, for the same quiet arithmetic of time'],
    updatedAt: '2026-05-28',
  },
  {
    id: 'i_paddington2',
    spaceId: 's_movies',
    slug: 'paddington-2',
    title: 'Paddington 2',
    brand: 'Paul King',
    image: { key: 'aura/dune', alt: 'Warm sand-toned abstract field', retina: false },
    description: 'A family film about a bear, a stolen pop-up book and a prison laundry.',
    creatorNote:
      'I am aware of how this reads next to the rest of this Space, and I am keeping it here anyway. It is constructed with more care than most films made for adults, and the prison sequence is genuinely one of the best-staged things I have seen. Put it on when the week has been bad.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2018',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['Every gag is set up properly and paid off', 'Kind without being soft'],
    dislikes: ['You have to get past the premise'],
    alternatives: ['The first film, which is nearly as good'],
    updatedAt: '2026-05-28',
  },
  {
    id: 'i_lahaine',
    spaceId: 's_movies',
    slug: 'la-haine',
    title: 'La Haine',
    brand: 'Mathieu Kassovitz',
    image: { key: 'aura/ink', alt: 'Cool ink-toned abstract field', retina: false },
    description: 'A black-and-white film following three friends over twenty-four hours in a Paris suburb.',
    creatorNote:
      'Thirty years old and it has not softened at all, which is the uncomfortable part. I watch it every few years to check whether I have started finding it comfortable. So far, no. The camera work is the reason I started paying attention to how a shot moves.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2016',
    frequency: 'occasionally',
    wouldBuyAgain: true,
    likes: ['The camera is a character in it', 'Ends on the only line it could end on'],
    dislikes: ['Bleak in a way that needs the right evening'],
    alternatives: ['Les Mis\u00e9rables (2019), which is in open conversation with it'],
    updatedAt: '2026-05-28',
  },
  {
    id: 'i_idea_slow',
    spaceId: 's_ideas',
    slug: 'buy-slowly',
    title: 'Buy slowly, keep longer',
    brand: null,
    image: { key: 'spaces/ideas', alt: 'A dark sphere catching one edge of light', retina: true },
    description: 'A working note on consumption.',
    creatorNote:
      'A rule I keep failing and returning to: wait thirty days on anything over a hundred pounds. Most of the list disappears on its own. The things that survive the wait are the things in this profile.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-16',
  },
  {
    id: 'i_idea_public',
    spaceId: 's_ideas',
    slug: 'working-in-public',
    title: 'Unfinished work, in public',
    brand: null,
    image: { key: 'aura/slate', alt: 'Cool abstract light field', retina: false },
    description: 'A working note on process.',
    creatorNote:
      'Publishing something half-formed is how I find out whether it is worth finishing. The cost is looking uncertain in public, which is a smaller cost than it feels.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-16',
  },
  {
    id: 'i_idea_disclose',
    spaceId: 's_ideas',
    slug: 'disclose-first',
    title: 'Disclose before anyone asks',
    brand: null,
    image: { key: 'detail/deck', alt: 'Close detail of a worn surface under raking light', retina: false },
    description: 'A working note on recommendations.',
    creatorNote:
      'If a label would embarrass me, that is the exact reason to put it on. Every paid, gifted and affiliate item in this profile says so on its own tile, before you click. The cost is that the sponsored things look worse than the bought ones. That is the correct outcome and it is the only version of this I am willing to run.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-16',
  },
  {
    id: 'i_idea_month',
    spaceId: 's_ideas',
    slug: 'a-month-before-it-counts',
    title: 'Nothing here until I have lived with it a month',
    brand: null,
    image: { key: 'detail/ridge', alt: 'Close detail of a ridged surface', retina: false },
    description: 'A working note on reviewing.',
    creatorNote:
      'A first impression is a description of the packaging. Almost everything is good for a week. The failures on this profile — the tripod I never carry, the case that is too heavy — only showed up in month three, and those are the entries people write to me about.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-16',
  },
  {
    id: 'i_idea_dislikes',
    spaceId: 's_ideas',
    slug: 'keep-the-dislikes-in',
    title: 'Keep the dislikes in',
    brand: null,
    image: { key: 'detail/surf', alt: 'Close detail of moving water', retina: false },
    description: 'A working note on writing about things.',
    creatorNote:
      'A recommendation with no drawbacks listed is an advert that has not admitted it. Every item here carries what I dislike about it, including the things I would buy again tomorrow. It makes the page longer and it is the only reason any of it is worth reading.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-16',
  },
  {
    id: 'i_morning',
    spaceId: 's_life',
    slug: 'morning-walk',
    title: 'The first hour, outside',
    brand: null,
    image: { key: 'spaces/life', alt: 'Ocean surf under an overcast sky', retina: true },
    description: 'A daily routine.',
    creatorNote:
      'An hour outside before the first screen. It is the only habit on this profile I have kept for more than three years without a gap.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2021',
    frequency: 'daily',
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-01',
  },
  {
    id: 'i_coffee',
    spaceId: 's_life',
    slug: 'hand-grinder',
    title: 'Hand coffee grinder',
    brand: '1Zpresso',
    image: { key: 'plinth/studio', alt: 'Hand coffee grinder', retina: false },
    description: 'A stainless burr hand grinder.',
    creatorNote:
      'Two minutes of effort every morning that I have come to like. Travels well, never needs power.',
    price: 159,
    retailer: 'Specialist coffee shop',
    productUrl: 'https://example.com/shop/hand-grinder',
    disclosure: 'purchased',
    usedSince: 'March 2023',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Grind consistency matches electric grinders costing far more', 'Packs for travel'],
    dislikes: ['It is still two minutes of work before coffee'],
    alternatives: ['Timemore C3 for roughly half'],
    updatedAt: '2026-09-01',
  },
  {
    id: 'i_sixmeals',
    spaceId: 's_life',
    slug: 'six-meals-on-rotation',
    title: 'Six meals, on rotation',
    brand: null,
    image: { key: 'aura/dune', alt: 'Warm sand-toned abstract field', retina: false },
    description: 'A domestic habit.',
    creatorNote:
      'I cook the same six things and I stopped apologising for it around 2023. Deciding what to eat was costing more of the evening than the cooking did. The variety went down and the quality went up, because after the fortieth time you are actually good at it.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2023',
    frequency: 'daily',
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-01',
  },
  {
    id: 'i_castiron',
    spaceId: 's_life',
    slug: 'cast-iron-pan',
    title: 'Cast-iron frying pan',
    brand: null,
    image: { key: 'plinth/studio', alt: 'Heavy cast-iron pan on a dark plinth', retina: false },
    description: 'A 26cm pre-seasoned cast-iron skillet.',
    creatorNote:
      'Thirty pounds, bought in 2019, and it will outlive every other object in this profile including the camera. Five of the six meals above happen in it. It is heavy enough that I do not use it for anything quick, and it rusts in a week if you leave it wet.',
    price: 30,
    retailer: 'Local kitchen shop',
    productUrl: 'https://example.com/shop/cast-iron-pan',
    disclosure: 'purchased',
    usedSince: '2019',
    frequency: 'daily',
    wouldBuyAgain: true,
    likes: ['Improves with use rather than wearing out', 'Goes from hob to oven without thinking'],
    dislikes: ['Too heavy to reach for casually', 'Rusts quickly if left wet'],
    alternatives: ['Carbon steel for most of the same behaviour at half the weight'],
    updatedAt: '2026-09-01',
  },
  {
    id: 'i_reset',
    spaceId: 's_life',
    slug: 'sunday-reset',
    title: 'Ninety minutes on a Sunday',
    brand: null,
    image: { key: 'scenes/ocean', alt: 'Open water under flat grey light', retina: true },
    description: 'A weekly habit.',
    creatorNote:
      'Wash, tidy, cook for two days, write down the three things that actually matter this week. It is the least interesting entry on this profile and it is the reason the rest of the week works. When I skip it I can tell by Tuesday.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: '2022',
    frequency: 'weekly',
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-09-01',
  },
  {
    id: 'i_dolomites',
    spaceId: 's_memories',
    slug: 'dolomites-2023',
    title: 'Dolomites, June 2023',
    brand: null,
    image: { key: 'spaces/memories', alt: 'Amber mountain range at sunrise', retina: true },
    description: 'Eight days walking in northern Italy.',
    creatorNote:
      'The trip that made me take photography seriously rather than treating it as a thing I did on holiday. Most of what is in the Photography Space was bought because of this week.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-06-14',
  },
  {
    id: 'i_mem_lisbon',
    spaceId: 's_memories',
    slug: 'lisbon-winter-2021',
    title: 'Lisbon, winter 2021',
    brand: null,
    image: { key: 'scenes/night-glass', alt: 'City lights refracted through dark glass', retina: true },
    description: 'Six weeks working from a rented room above a bakery.',
    creatorNote:
      'The first time I worked somewhere that was not my own desk for long enough to stop being a holiday. I came back with almost no photographs and a completely different idea of how much space I need. Most of what got thrown out in 2022 was decided in that room.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-06-14',
  },
  {
    id: 'i_mem_firstroll',
    spaceId: 's_memories',
    slug: 'the-first-roll',
    title: 'The first roll I developed myself',
    brand: null,
    image: { key: 'detail/lens', alt: 'Close detail of a lens element catching light', retina: false },
    description: 'Thirty-six frames, of which four survived.',
    creatorNote:
      'I ruined most of it and hung the rest in the bathroom overnight. Four frames came out, all of them of the same window. I still have them, and I still think about the gap between what I meant to take and what the chemistry gave back.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-06-14',
  },
  {
    id: 'i_mem_galloway',
    spaceId: 's_memories',
    slug: 'two-weeks-offline',
    title: 'Two weeks offline, Galloway',
    brand: null,
    image: { key: 'scenes/forest', alt: 'Dense forest under low cloud', retina: true },
    description: 'A fortnight in a cottage with no signal and no plan.',
    creatorNote:
      'I took three books and finished one. The first four days were genuinely unpleasant and I have never recommended anything more strongly since. The Ideas Space exists because of the notebook I filled in the second week.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-06-14',
  },
  {
    id: 'i_mem_manchester',
    spaceId: 's_memories',
    slug: 'manchester-2024',
    title: 'Finishing badly, Manchester 2024',
    brand: null,
    image: { key: 'scenes/fog-ridge', alt: 'A ridge line disappearing into fog', retina: true },
    description: 'A first marathon, forty minutes slower than planned.',
    creatorNote:
      'I went out too fast, paid for it from mile eighteen and walked twice. It is in here rather than left out because the training that came after it is the reason the Fitness Space looks the way it does. The plan was wrong, not the legs.',
    price: null,
    retailer: null,
    productUrl: null,
    disclosure: 'editorial',
    usedSince: null,
    frequency: null,
    wouldBuyAgain: null,
    likes: [],
    dislikes: [],
    alternatives: [],
    updatedAt: '2026-06-14',
  },
]);
