/**
 * Alex Den — the flagship Zat.
 *
 * Space titles, descriptors and captions are taken verbatim from the supplied
 * reference compositions so the built product reads identically to them.
 * Alex is a fictional creator; the imagery is extracted from those references.
 */
import type { Person, Space } from '@/lib/schema';

export const alex: Person = {
  id: 'p_alex',
  handle: 'alexden',
  name: 'Alex Den',
  roles: ['Designer', 'Creator', 'Explorer'],
  statement:
    'I keep one place for the things that actually shape how I work and live — what I wear, what I read, what I shoot with, and what I keep coming back to.',
  location: 'Seoul, KR',
  timezone: 'Asia/Seoul',
  avatar: { key: 'avatars/alex-den', alt: 'Portrait of Alex Den', retina: false },
  portrait: {
    key: 'portrait/alex-den',
    alt: 'Alex Den standing, full length, in a burgundy knit sweater',
    retina: false,
  },
  photoUrl: null,
  character: null,
  socials: [
    { network: 'instagram', handle: '@alexden', url: 'https://example.com/social/alexden' },
    { network: 'x', handle: '@alex.archive', url: 'https://example.com/social/alex-archive' },
    { network: 'website', handle: 'alexden.xyz', url: 'https://example.com/alexden' },
    { network: 'linkedin', handle: 'alexden', url: 'https://example.com/social/in-alexden' },
    { network: 'dribbble', handle: 'alexden', url: 'https://example.com/social/dribbble-alexden' },
  ],
  theme: {
    accent: 'bronze',
    background: 'void',
    typeset: 'editorial',
    motion: 'full',
    cardScale: 'balanced',
  },
  plan: 'pro',
  published: true,
  joinedAt: '2024-03-18',
  updatedAt: '2026-09-12',
};

export const alexSpaces: Space[] = [
  {
    id: 's_wardrobe',
    personId: 'p_alex',
    slug: 'wardrobe',
    index: 1,
    title: 'Wardrobe',
    descriptor: 'Good Outfits\nBetter Days.',
    caption: 'Style\nMy Way.',
    intro:
      'I buy slowly and wear things until they fall apart. Most of what is here has survived at least three winters. Nothing in this Space was chosen because it photographed well — it is here because I reach for it without thinking.',
    note: 'I re-check this Space every season and remove anything I have not worn in a year.',
    cover: { key: 'spaces/wardrobe', alt: 'Folded burgundy knit sweater on a pale surface', retina: true },
    layout: 'text-left',
    size: 'lg',
    featured: true,
    order: 1,
    updatedAt: '2026-09-02',
  },
  {
    id: 's_music',
    personId: 'p_alex',
    slug: 'music',
    index: 2,
    title: 'Music',
    descriptor: 'Sounds that\nmove me.',
    caption: 'Play\nFeel\nRepeat.',
    intro:
      'Headphones on for most of the working day. This is the gear I actually listen through and the records that keep surviving my library clear-outs.',
    note: null,
    cover: { key: 'spaces/music', alt: 'Matte black over-ear headphones in low light', retina: true },
    layout: 'text-left',
    size: 'md',
    featured: true,
    order: 2,
    updatedAt: '2026-08-21',
  },
  {
    id: 's_travel',
    personId: 'p_alex',
    slug: 'travel',
    index: 3,
    title: 'Travel',
    descriptor: 'New places.\nNew perspectives.',
    caption: 'Explore\nMore',
    intro:
      'Six or seven trips a year, usually with more camera gear than clothing. What lives here is the kit that survives airports and the places worth the flight.',
    note: 'Packing list is at the bottom. It has not changed much in two years.',
    cover: { key: 'spaces/travel', alt: 'Jagged mountain peaks rising through morning fog', retina: true },
    layout: 'text-left',
    size: 'md',
    featured: true,
    order: 3,
    updatedAt: '2026-09-09',
  },
  {
    id: 's_memories',
    personId: 'p_alex',
    slug: 'memories',
    index: 4,
    title: 'Memories',
    descriptor: 'Moments\nthat matter.',
    caption: 'A Kinder\nVersion of Me',
    intro:
      'Not everything in a life is a recommendation. This Space is the one that is just mine — places, dates and a few photographs I would keep if I lost the rest.',
    note: null,
    cover: { key: 'spaces/memories', alt: 'Amber mountain range at sunrise', retina: true },
    layout: 'text-left',
    size: 'lg',
    featured: false,
    order: 4,
    updatedAt: '2026-06-14',
  },
  {
    id: 's_books',
    personId: 'p_alex',
    slug: 'books',
    index: 5,
    title: 'Books',
    descriptor: 'A calmer mind.\nA louder life.',
    caption: 'Read\nThink\nReturn.',
    intro:
      'I re-read more than I read. These are the five I have gone back to most, with honest notes on which ones actually changed something and which ones just sounded like they would.',
    note: 'Marked with what I took from each one rather than a star rating.',
    cover: { key: 'spaces/books', alt: 'A fanned stack of well-read paperbacks', retina: true },
    layout: 'text-left',
    size: 'xl',
    featured: true,
    order: 5,
    updatedAt: '2026-09-11',
  },
  {
    id: 's_work',
    personId: 'p_alex',
    slug: 'work',
    index: 6,
    title: 'Work',
    descriptor: 'Ideas into\nreal impact.',
    caption: 'Build\nCreate\nImprove',
    intro:
      'Product and brand design, mostly for small teams. The tools here are the ones still open at the end of a long week.',
    note: null,
    cover: { key: 'spaces/work', alt: 'Laptop on a desk under soft studio light', retina: true },
    layout: 'text-left',
    size: 'md',
    featured: true,
    order: 6,
    updatedAt: '2026-09-05',
  },
  {
    id: 's_photography',
    personId: 'p_alex',
    slug: 'photography',
    index: 7,
    title: 'Photography',
    descriptor: 'Finding beauty\nin the everyday.',
    caption: 'Look\nAgain.',
    intro:
      'The camera bag, exactly as it is packed right now. Every piece here has been on at least one trip, and I have written down what I dislike about each of them too.',
    note: 'If you are starting out, read the note on the 35mm before you buy the body.',
    cover: { key: 'spaces/photography', alt: 'Mirrorless camera body with a prime lens attached', retina: true },
    layout: 'text-left',
    size: 'lg',
    featured: true,
    order: 7,
    updatedAt: '2026-09-14',
  },
  {
    id: 's_fitness',
    personId: 'p_alex',
    slug: 'fitness',
    index: 8,
    title: 'Fitness',
    descriptor: 'A stronger\ntomorrow.',
    caption: 'Discipline\nFeels Good',
    intro:
      'Four sessions a week, nothing complicated. A small amount of equipment that gets used constantly beats a room full of things that do not.',
    note: null,
    cover: { key: 'spaces/fitness', alt: 'Matte black dumbbell on a dark surface', retina: true },
    layout: 'text-left',
    size: 'md',
    featured: false,
    order: 8,
    updatedAt: '2026-08-30',
  },
  {
    id: 's_gaming',
    personId: 'p_alex',
    slug: 'gaming',
    index: 9,
    title: 'Gaming',
    descriptor: 'Play\nRecharge\nLevel Up',
    caption: 'Good Games\nBetter Moods',
    intro:
      'Mostly single-player, mostly late at night, mostly things with a good soundtrack. A short list because I finish about four games a year.',
    note: null,
    cover: { key: 'spaces/gaming', alt: 'Black game controller lit from one side', retina: true },
    layout: 'text-left',
    size: 'md',
    featured: false,
    order: 9,
    updatedAt: '2026-07-19',
  },
  {
    id: 's_movies',
    personId: 'p_alex',
    slug: 'movies',
    index: 10,
    title: 'Movies',
    descriptor: 'Stories\nthat stay.',
    caption: 'Different Worlds\nSame Human',
    intro:
      'Films I have watched more than twice, and the reason each one earned the rewatch. Heavy on science fiction, which I make no apology for.',
    note: null,
    cover: { key: 'spaces/movies', alt: 'Figure silhouetted against an amber haze', retina: true },
    layout: 'text-left',
    size: 'md',
    featured: false,
    order: 10,
    updatedAt: '2026-05-28',
  },
  {
    id: 's_ideas',
    personId: 'p_alex',
    slug: 'ideas',
    index: 11,
    title: 'Ideas',
    descriptor: 'Random thoughts.\nBetter tomorrows.',
    caption: 'Small Ideas\nBig Changes',
    intro:
      'Unfinished thinking, kept in public on purpose. Some of these will turn into work and most of them will not.',
    note: null,
    cover: { key: 'spaces/ideas', alt: 'A dark sphere catching a single edge of light', retina: true },
    layout: 'tile',
    size: 'sm',
    featured: false,
    order: 11,
    updatedAt: '2026-09-16',
  },
  {
    id: 's_life',
    personId: 'p_alex',
    slug: 'life',
    index: 12,
    title: 'Life',
    descriptor: 'A collection\nof everything me.',
    caption: 'Same Person\nNew Horizons',
    intro:
      'The parts that do not fit anywhere else — routines, small rituals, the things that keep the rest of it working.',
    note: null,
    cover: { key: 'spaces/life', alt: 'Ocean surf breaking under an overcast sky', retina: true },
    layout: 'text-left',
    size: 'lg',
    featured: false,
    order: 12,
    updatedAt: '2026-09-01',
  },
];
