/**
 * Downloads the woff2 files Zat needs and writes a self-hosted @font-face sheet.
 *
 * Google Fonts is the only asset host reachable from this environment, and we
 * self-host the result so the running site makes no third-party requests.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const OUT_DIR = resolve(import.meta.dirname, '../public/fonts');
const CSS_OUT = resolve(import.meta.dirname, '../src/styles/fonts.css');

// A modern UA is required or Google serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36';

/** Subsets we keep: enough for European names without shipping the whole world. */
const KEEP = new Set(['latin', 'latin-ext']);

type Face = {
  family: string;
  weight: string;
  style: string;
  subset: string;
  url: string;
  unicodeRange: string;
};

const FAMILIES = [
  { name: 'Playfair Display', spec: 'Playfair+Display:ital,wght@0,400;0,500;0,600;0,700' },
  { name: 'Inter', spec: 'Inter:wght@300;400;500;600;700' },
];

async function fetchCss(spec: string): Promise<string> {
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Font CSS ${spec} failed: ${res.status}`);
  return res.text();
}

/** Google's css2 output is a run of @font-face blocks each preceded by a subset comment. */
function parseFaces(css: string, family: string): Face[] {
  const faces: Face[] = [];
  const blocks = css.split('/*').slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (!KEEP.has(subset)) continue;
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '';
    if (!url) continue;
    faces.push({ family, weight, style, subset, url, unicodeRange });
  }
  return faces;
}

function fileNameFor(f: Face): string {
  const slug = f.family.toLowerCase().replace(/\s+/g, '-');
  return `${slug}-${f.weight}-${f.style}-${f.subset}.woff2`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const all: Face[] = [];

  for (const fam of FAMILIES) {
    const css = await fetchCss(fam.spec);
    const faces = parseFaces(css, fam.name);
    if (!faces.length) throw new Error(`No usable faces parsed for ${fam.name}`);
    all.push(...faces);
  }

  const lines: string[] = [
    '/* Self-hosted fonts. Generated by scripts/fetch-fonts.ts — do not edit by hand. */',
    '',
  ];

  for (const f of all) {
    const name = fileNameFor(f);
    const res = await fetch(f.url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`Download failed for ${name}: ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    await writeFile(resolve(OUT_DIR, name), buf);
    lines.push(
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      '  font-display: swap;',
      `  src: url('/cx/fonts/${name}') format('woff2');`,
      f.unicodeRange ? `  unicode-range: ${f.unicodeRange};` : '',
      '}',
      '',
    );
    console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)}kb`);
  }

  await writeFile(CSS_OUT, lines.filter((l) => l !== '').join('\n') + '\n', 'utf8');
  console.log(`\n${all.length} faces written to public/fonts + src/styles/fonts.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
